# export.py
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from io import BytesIO
from datetime import datetime


def export_chat_to_pdf(chat_name: str, messages: list) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=20,
        textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=6,
        alignment=TA_CENTER
    )

    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=20,
        alignment=TA_CENTER
    )

    user_style = ParagraphStyle(
        'UserMessage',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#ffffff'),
        backColor=colors.HexColor('#4a90d9'),
        borderPadding=(8, 8, 8, 8),
        spaceAfter=8,
        leftIndent=60,
        borderRadius=8
    )

    assistant_style = ParagraphStyle(
        'AssistantMessage',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#1a1a1a'),
        backColor=colors.HexColor('#f0f0f0'),
        borderPadding=(8, 8, 8, 8),
        spaceAfter=8,
        rightIndent=60,
        borderRadius=8
    )

    label_user_style = ParagraphStyle(
        'LabelUser',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#4a90d9'),
        spaceAfter=2,
        leftIndent=60
    )

    label_assistant_style = ParagraphStyle(
        'LabelAssistant',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey,
        spaceAfter=2,
    )

    story = []

    # Title
    story.append(Paragraph("🎓 AA AI Mentor", title_style))
    story.append(Paragraph(f"Chat Export: {chat_name}", subtitle_style))
    story.append(Paragraph(
        f"Exported on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        subtitle_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Spacer(1, 20))

    # Messages
    for msg in messages:
        role = msg.get("role")
        content = msg.get("content", "")

        # Clean content for PDF
        content = content.replace("✅", "").replace("📅", "").replace("📹", "")
        content = content.replace("<", "&lt;").replace(">", "&gt;")

        if role == "user":
            story.append(Paragraph("You:", label_user_style))
            story.append(Paragraph(content, user_style))
        elif role == "assistant":
            story.append(Paragraph("AI Mentor:", label_assistant_style))
            story.append(Paragraph(content, assistant_style))

        story.append(Spacer(1, 6))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Paragraph(
        "Generated by Ansar's AI Mentor — Informatics and Digital Pedagogy",
        subtitle_style
    ))

    doc.build(story)
    return buffer.getvalue()